# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC  # Added alias
from selenium.webdriver.common.action_chains import ActionChains

class TestOpenGraph():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_openGraph(self):
    self.driver.get("http://0.0.0.0:8000/indexTest.html")
    self.driver.set_window_size(1854, 1011)
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(1) > .geBtn").click()
    self.driver.switch_to.default_content()
    #self.driver.find_element(By.LINK_TEXT, "File").click()
    wait = WebDriverWait(self.driver, 10)
    # Get current window size
    window_size = self.driver.get_window_size()
    width = window_size['width']
    height = window_size['height']

    # Reference resolution and coordinates
    ref_width = 1854
    ref_height = 1011
    orig_x = 28
    orig_y = 127

    # Convert to relative
    rel_x = orig_x / ref_width
    rel_y = orig_y / ref_height

    # Scale to current screen size
    x = int(width * rel_x)
    y = int(height * rel_y)

    # Small delay for safety

    # Move and click at (x, y)
    actions = ActionChains(self.driver)
    actions.move_by_offset(x, y).click().perform()

    # Reset the mouse position (important if you want to click again later)
    actions.move_by_offset(-x, -y).perform()

